### PR TITLE
Create nsp14_nsp10_rna_namd_trajectories_dry_amarolab_new.yml

### PR DESCRIPTION
**Pull request by ozlemd78**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
I need to request you put all the changes into one PR at this point. Its becoming increasingly difficult to keep track of which PR's need to be merged and where the conversations we're having are. 

If you need to, you can open the one PR like you are doing through the website, then go into that opened branch on your fork and directly add/modify the files on that branch. It will propagate the changes to the single, already open PR. Having a large number of commits on one PR is much easier than managing many PRs of single commits.

**Comment by ozlemd78** [comment]
Hi Levi,

I am sorry for the confusion.
I have 3 pull requests with full and accurate info now for 3 trajectories.
#259, #260 and #261.
I would really appreciate if you can process them.

All previous files in "simulations" folder from me can be deleted.

I will try making the remaining 3 trajectories into one PR.
I am really trying to understand how Github works. It isn't
straightforward to me yet.

Best,
Ozlem

**Comment by Lnaden** [comment]
Okay. I'll merge the three PR's you listed.

What I was suggesting doing is opening one PR like you have been, then navigating to your own repo (you can use the link at the top of the PR here where it says: 

[ozlemd78](https://github.com/ozlemd78) wants to merge 1 commit into [MolSSI:master](https://github.com/MolSSI/covid) from [ozlemd78:patch-20](https://github.com/ozlemd78/covid/tree/patch-20)

You can click on the [ozlemd78:patch-20](https://github.com/ozlemd78/covid/tree/patch-20) link and it will take you there. Then just do exactly what you did to start the PR, but instead of accepting the defaults at the bottom you should be able to choose to "directly merge into {whatever the branch you are on is}." like the image below.

image 

Then any changes you are making on your fork on that branch which is the same one this PR is trying to merge from will show up here.

No need to do that right now since I'm going to merge the three PRs. If you're wanting to learn or practice with git some more, I would suggest making a PR where you delete the files on your fork and branch, then open a PR here. It would show you the basic flow of git, github, forks, branches, and PRs.

**Comment by ozlemd78** [comment]
Thanks much Levi!
I got it working finally and merged the remaining 3 files
in one PR.

Best,
Ozlem

**Comment by Lnaden** [comment]
Great! I do suggest you also try to do this from the command line with `git` instead of through the web browser. Its much more straightforward and easier to do instead of having to go in file by file through the GUI here.

**Pull request merged**
