### PR TITLE
Create nsp14_nsp10_namd_trajectories_dry_amarolab.yml

### PR DESCRIPTION
**Pull request by ozlemd78**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
@ozlemd78 can you please set the `trajectory` URL to the actual trajectory URL and not just the lab homepage? I'm going to hold off on merging any of the other files right now until thats resolved.

**Comment by ozlemd78** [comment]
Hi Levi,

The exact link for this trajectory is
https://amarolab.ucsd.edu/files/covid19/CoV2_ExoN/nsp14_nsp10/trajectories_nsp14_nsp10_namd_dry_amarolab.dcd.gz

I couldn't find where to edit the file and make this change.
Can you help please?

Best,
Ozlem

**Comment by Lnaden** [comment]
What you have done here is make a PR to the repository using the GitHub web interface. That's fine for making very short or small changes/edits to single file, but runs into the issue you have where if you then need to edit it, it gets to be more problematic.

When you made a PR through the web here, GitHub automatically made a [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) of this central repository in your personal user repo here: https://github.com/ozlemd78/covid. It then also made a [branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) called `patch-X` where X is just an increment of how many times you've used the website to open PR's on this central repo. Its a default name, you could have called it whatever.

One option is to go to the [`patch-10` branch on your fork](https://github.com/ozlemd78/covid/tree/patch-10), edit the file there directly, and commit the file directly to your fork *without opening as a PR*, it should be a radio button at the bottom before you click submit (or something). That will automatically update this PR as well on the main repo.

The more complete approach is to use `git` from your local computer, do a [`git pull`](https://github.com/git-guides/git-pull) of your fork and branch to your local filesystem, edit the files as normal, do a [`git add`](https://github.com/git-guides/git-add) and [`git commit`](https://github.com/git-guides/git-commit) to confirm your changes to the local `git` repository, and finally do a [`git push`](https://github.com/git-guides/git-push) to upload those changes to the repository on GitHub. This option is more complete because it allows multiple and arbitrary amounts of changes to any number of files, and you can verify everything before you upload. Then any modifications you need, you can just repeat the process of editing the files locally, add/committing them, then pushing to update the PR.

**Comment by ozlemd78** [comment]
Hi Levi,

I have made the changes using patch-10 link you sent
for nsp14_amber_trajectories_dry_amarolab.yml .

I don't see the changes yet when I look at the public files though,
does it take some time or am I missing something?

Best,
Ozlem

**Comment by ozlemd78** [comment]
Hi Levi,

Could you please cancel/reject all 6 of my pull requests today?
Or do I have to delete them?
I'd like to go ahead and generate fresh files with complete info and
make a pull request then.

Thanks much for your help,
Ozlem

**Comment by Lnaden** [comment]
> Could you please cancel/reject all 6 of my pull requests today

Not a problem. I can close all the open ones. 

> Thanks much for your help,

No problem, happy to help; especially when it comes to helping people learn git.

**Pull request closed without merging**
