### PR TITLE
Create Spike_6vxx_1_2_1_nowater.yml

### PR DESCRIPTION
**Pull request by ghorbanimahdi73**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Review by ghorbanimahdi73 — COMMENTED** [review]
The description was quoted.

**Comment by Lnaden** [comment]
Looks like the build and validation are passing. Just a last few things:

* The URL for the trajectory should be https://molssi-bioexcel-covid-19-structure-therapeutics-hub.s3.amazonaws.com/KlaudaGroup/spike_6VXX_1_2_1_nowater.gz I believe.
* The Model you provided in the list is not one which we are tracking in the Hub. Is it a model you created? If so, would you be willing to create the metadata file for it as well? It would go in `/data/models`. Similar to the simulation YAML files, it has its own scheme which you can see there.
* As a contributor, please feel free to add yourself to the `/data/contributors/people.yml` file so your name appears in our published contributors.
 
Otherwise, this is looking great! If you want to add the other simulation YAML file to this PR as well, feel free to do so.

**Comment by ghorbanimahdi73** [comment]
Hello Levi,

The model was provided by CHARMM-GUI which I have pointed out to their URL
in the description. I have made another pull request for the other model
(6VSB).

Best Regards,

Mahdi Ghorbani
PhD Candidate,
Chemical and Biomolecular Engineering
University of Maryland, College park, MD

**Comment by Lnaden** [comment]
The URL for the trajectory still needs updated. Could you update that and let me know when this is ready to be merged?

**Review by ghorbanimahdi73 — COMMENTED** [review]
The URL was changed

**Pull request merged**
