### PR TITLE
Adding links to FeigLab refined protein structure models.

### PR DESCRIPTION
**Pull request by sjayellis**
## Description
Adding models predicted and/or refined by the Feig Lab at Michigan State University.
Data hosted: https://github.com/feiglab/sars-cov-2-proteins

## Status
- [x] Adheres to the requested folder structure
- [x] Metadata is provided for each file
- [ ] Ready to go

### CODE REVIEW

**Comment by jchodera** [comment]
This is great! Once the `protein` and `structure` tags have settled in ~1 day, it would be great to add these to the YAML files too and then merge these in.

**Comment by Lnaden** [comment]
I'm going to hold off on merging this then until we get the tags sorted and unified

**Comment by sjayellis** [comment]
The tree of this has gotten messy. Going to close and reopen a new PR off the current master.

**Comment by Lnaden** [comment]
Did you try to pull master into this branch, or rebase into this branch?

**Comment by sjayellis** [comment]
I had rebased, but it was still not getting all of the changes from master. Since the pr was originally just supposed to add files it made more sense to just make a new one.

**Comment by Lnaden** [comment]
Yeah, doing `rebase master` does not do a `fetch` or `pull` first. You would want to either pull the remote into master first, or rebase from the remote directly. Either way, your solution will be fine

**Pull request closed without merging**
