### PR TITLE
Expanded Simulation Representation and Citations and aAdd 15us Sim data

### PR DESCRIPTION
**Pull request by Lnaden**
## Description
Expanded the capabilities of the `simulations` entries to support more
general data entries with more than 1 URL to the trajectory. This is
done through the new `trajectory_data` keyword which is exclusive
with `trajectory` + `size`. It allows arbitrary entry of headers and
items, rendering them in smaller tables as part of the larger entry.

The Validation script has been updated to correctly capture this schema.

The simulation page has been updated to show this type of data
while still maintaining the old style without breaking.

New Functionality: collapsed citations in simulations.

Resolved a long outstanding item to make the references and citations
which come as part of the metadata. These start as collapsed items which
can be expanded for space.

In addition, adds the 15.14 us Trajectories from Luc-Henri Jolly Jussieu and Jean-Philip Piquemal

Data drawn from its [original site](http://tinker-hp.ip2ct.upmc.fr/?Access-to-the-SARS_Cov2-Protease).
The engineering to make this render correctly is included as part of the
PR this is attached to.

Due to the file sizes, compressing to a single file was not feasible. It
would have been > 1TB.

Thanks to @lhjolly and @jppiquem for providing these data and the patience while I got the back-end engineering working.

## Status
- [x] YAML file for each piece of data
- [x] Ready to go

### CODE REVIEW

**Review by sjayellis — APPROVED** [review]
Looks good. I like that it makes the simulation entries more flexible to different data sets going forward.

**Comment by lhjolly** [comment]
Hi all,
Thanks for your valuable efforts!

1) I've uploaded the missing de-biasing score files on the S3 bucket. Their names have the general form clusterX_pca4_tinker-hp_red_de-biasing_score.txt. So you should change the place holders.
2) The biasing score files names have a typo (biasaing, should be biasing)
3) In the presentation, linksto the files are made to the original location (in Switzerland). I think it would be better to link to the MolSSI location

**Comment by Lnaden** [comment]
Fixed all of the changes requested, @lhjolly. If this all looks good, I'll merge it and it will go live.

**Comment by lhjolly** [comment]
Ok. Everything works ! 

May I ask to put the MISCELLANEOUS entries first, i.e. before the AMOEBA sampling, as it was on our web site ?
Also, can you remove "Jussieu" next to my name, and put "CNRS/Sorbonne Université/IP2CT" instead ?

**Comment by Lnaden** [comment]
Changes requested have been made. Are we good to go?

**Comment by lhjolly** [comment]
Yes ! Thanks again !

**Comment by Lnaden** [comment]
You're welcome. Here is the permanent link to that entry: https://covid.molssi.org//simulations/#amoeba-1514-microsecond-trajectory-of-main-protease

**Comment by lhjolly** [comment]
Hi again, 
I just saw that our paper is shown as a preprint. It has been published now. I forgot to update our web site. Here is the  definitive reference :

“Jaffrelot Inizan, Theo; Célerse, Frédéric; Adjoua, Olivier; El Ahdab, Dina; Jolly, Luc-Henri; Liu, Chengwen; et al. (2020): High-Resolution Mining of SARS-CoV-2 Main Protease Conformational Space: Supercomputer-Driven Unsupervised Adaptive Sampling.”  Chem. Sci., 2021,12, 4889-4907 (DOI: https://doi.org/10.1039/D1SC00145K)

Can you please update the entry ?
Cheers

**Comment by Lnaden** [comment]
Updated in a separate PR.

**Comment by lhjolly** [comment]
Thanks !

**Comment by lhjolly** [comment]
Hi Levi,

I checked the vmd command, and it appears it misses the -f flag. So, the correct command should be.
vmd -f AMOEBA_15mics_sampling/6lu7_rec_GMX_conf.pdb AMOEBA_15mics_sampling/sampling_iteration*/protein.dcd

can you please update the web site ?
I'm sorry for this stupid mistake.

Cheers,

**Comment by Lnaden** [comment]
Happy to fix it, no problems. I have the change made in #213. 

Feel free to open PR's yourself from a fork if you ever need to update or augment the entry. That way you're not waiting on me to go in and tweak it.

**Pull request merged**
