### PR TITLE
Coarse-grain trajectory of SARS-CoV2 Main Protease with SIRAH force field

### PR DESCRIPTION
**Pull request by PabloGGaray**
## Description
Trajectory of a 15 microseconds-long coarse-grained molecular dynamics simulation of SARS-CoV2 Main protease in its APO form. Created with the SIRAH force field.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by PabloGGaray** [comment]
Hi, I can't find where is the error in the "Schema Validation". I think that the descriptions in the "Details" point to the "references" but I don't understand where is the problem.

**Comment by Lnaden** [comment]
I think this is a problem with YAML interpreting the `:` in the reference as a dictionary mapping instead of one long string. Wrap each one of the reference list items in quotes, that should fix it.

**Comment by PabloGGaray** [comment]
This looks good and could be merged if you don't see a big error in the file.

Another question, this simulation, and others, that I going to be loading the entrances, were made using the structure from the PDB. In order to add the `model` tag, do I have to add a description of the PDB entry in the `models` directory? This is not necessary now but could be useful to make finding data easier.

**Comment by Lnaden** [comment]
The file looks fine.

We prefer you have `structures` and `models` referenced in the entries added to the Hub as well. Having those auto-link any simulations you add to the relevant structures and models. We're happy to help you fill in those gaps if you have any questions about them.

We do distinguish between the terms.
* `structures` are experimentally resolved entries, which also included most everything in the PDB
* `models` are derived and/or integrated structures from multiple data sources prepared for different tasks such as docking, FEP, virtual screening, etc. Effectively ready to go constructed molecular systems which can be used as inputs for myriad scientific research techniques.

`simulations` entries require at least one `structure`, but can also have any number of `models` as references.

**Pull request merged**
