### PR TITLE
Add in the R/Y/G citation system

### PR DESCRIPTION
**Pull request by Lnaden**
## Description
Updated the review process to be much more open and accepting with a system to have discussions through github issues

Added a Red / Yellow / Green (RYG, R/Y/G) system to most data types which are generated by people for "no publication," "has preprint or submitted," and "published," respectively. Auto generates based on YAML keys (and RCSB for structures)

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by jchodera** [comment]
> Added a Red / Yellow / Green (RYG, R/Y/G) system to most data types which are generated by people for "no publication," "has preprint or submitted," and "published," respectively. Auto generates based on YAML keys (and RCSB for structures)

I...is this useful?

I mean, why not just add a link to the preprint and/or a link to the published paper DOI? Why introduce a totally unnecessary stoplight system that doesn't actually help people find information? 

Also, a stoplight system tied to publication could mistakenly suggest that published papers are somehow more trustworthy than preprints, which is certainly not the case.

**Comment by jchodera** [comment]
Also, many high quality structures are showing up with red stoplights, which is definitely not what we want.

**Comment by Lnaden** [comment]
The RYG system is to indicate whether or not a datum has undergone an official, regulated, peer review process at a glance. We're trying to remain as neutral as we can on the mater and are simply accepting data, leaving mechanisms such as issues and project boards for the community and teams to have  discussions on the data.  If need be, we transfer the discussions to another public facing system if discussing through issues isn't suitable. As the reviews come in and consensus is reached from the community based on both usefulness and quality, we can take advantage of the rating system or some equivalent to indicate what the top data are.

We are going to be keeping an ear open for community feedback on the subject though, and if people do not like this system, we can work on a replacement.

**Comment by eriklindahl** [comment]
Red does not mean "bad", just that nobody has had a look at that particular entry *yet*. If one does not feel that indication is useful, the easy solution is of course to just ignore it and use all data :-)

However, in particular as we open up and allow anybody to submit anything, we need to at least be prepared for how to handle less-than-ideal submissions. An alternative could be to use "no color" instead of red to empasize that it hasn't been checked, not that it's considered bad.

I don't really believe in strict definitions for the quality system, but I prefer to think of it as

1. Unclassified
2. Enough extra information that I can at least try to assess the quality
3. At least one other person has already done #2 and thinks it might be good enough to be useful

For things like structures with a PDB ID and a preprint available from a trustworthy group, I don't think we need any motivation whatsoever to mark it as likely to be useful.

**Pull request merged**
