### PR TITLE
Bk nsp13 target yml

### PR DESCRIPTION
**Pull request by Binikarki**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
It looks like the YAML file is a bit mangled (possible tab character instead of space?)

Can you also please resolve the conflict files?

**Comment by jchodera** [comment]
@Binikarki You might want to start with a clean fork of the MolSSI repo and then just copy over the files you want to a clean branch, and open a new PR!

**Comment by jchodera** [comment]
@Binikarki You might want to start with a clean fork of the MolSSI repo and then just copy over the files you want to a clean branch, and open a new PR!

**Comment by Lnaden** [comment]
Woo! If this all passes, I think we'll be good to go

**Pull request closed without merging**
