### PR TITLE
Remove red marker from data, to give the system a neutral, yellow, green

### LINKED ISSUE #68: Remove stoplights from structural data
We need to remove the stoplights from structural data. They are entirely misleading as to the quality of the structures and their utility for different purposes.

Publication status has no impact on structure quality. If we want to communicate publication status as presence of preprint or published version, we should simply come up with an icon that is displayed for preprint and published that shows up if these are available and absent if they are not.

This is going to cause active harm to the community if we keep these. 

The appropriate annotation data should instead be pulled from the [Coronavirus Structural Task Force](https://github.com/thorn-lab/coronavirus_structural_task_force), but we shouldn't wait for the implementation of that to strip out the stoplight nonsense.

### PR DESCRIPTION
**Pull request by Lnaden**
## Description
This changes the Red/Yellow/Green marker for unreviewed, pre-print, reviewed to be a {no indicator}/yellow/green marker system to mean the same thing. 

Should help reduce the confusion which may be ingrained from people seeing red "stop" like shape.

Fixes #68 (possibly)

cc @jchodera @eriklindahl 

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
@jchodera I have changed up the symbols to use the OC SHERPA/RoMEO symbols to indicate pre-print and publication. They are a bit bulky, so ideas on how to shrink them would be helpful.

I was thinking I cut out all the extra words/description in the arrow and shrink the height down. I should be allowed to do that, even under the CC BY-NC-ND since its a formatting change and I still call out to the original in the about.

**Comment by Lnaden** [comment]
Make the markers better, found the original source and adapted it since it was under a better license (CC BY). The image was apparently under base Wikimedia stuff, and simply referenced SHERPA/RoMEO. This should be good to go at this point.

**Comment by jchodera** [comment]
Looks great! 

I'd just suggest:
* Allow _both_ preprint and published icons to be shown, since (1) the published version is often not open access, and (2) this could encourage preprinting
* I'd show preprint first and then published second

**Comment by Lnaden** [comment]
That's a great suggestion and decently easy to add in, I'll get that in today!

**Pull request merged**
