### PR TITLE
CG MD trajectories for PDBs 6W4H, 6YHU and 6W41

### PR DESCRIPTION
**Pull request by PabloGGaray**
## Description  
SIRAH CG MD trajectories for:  
- 6W4H: NSP16 - NSP10 Complex.  
- 6YHU: nsp7-nsp8 complex.  
- 6W41: S1 Receptor Binding Domain in complex with human antibody CR3022.

## Status
- [x] YAML file for each piece of data
- [x] Ready to go

### CODE REVIEW

**Comment by PabloGGaray** [comment]
Hi, I can't see the **6W41** entry in the preview, the other two entries are there. I don't see an error message in the checks, if you can tell me where the error is, I will fix it. Thank you.

**Comment by Lnaden** [comment]
Let me take a look.

**Comment by Lnaden** [comment]
I see what happened. The short is the `proteins` for the 6W41 entry needs to have a `- spike` under its list instead of `- RBD`, although it can have both without harm.

We haven't worked out the best way to organize by subunits yet, even though we do allow them as a valid "protein" in the validation check as a future potential feature.

If that solution works for you, feel free to make the change. If you would much rather have the subunit checked for, I can engineer a solution, but it might a while to implement.

**Comment by PabloGGaray** [comment]
@Lnaden Your solution work perfectly, this is ready to merge, thanks you.

**Pull request merged**
