### PR TITLE
CG mappings of Covid proteins added

### PR DESCRIPTION
**Pull request by geemi725**
CG mappings for several COVID-related proteins are added under data/models with links to the mapped files. 

TODO:
Update readme?

## Status
-  [ x]  YAML file for each piece of data
-  [ x]  Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
Is this ready to go in?

**Comment by geemi725** [comment]
Yes, ready to go!

**Comment by Lnaden** [comment]
Great. One last check from my end, have you added yourself and anyone who helped on this work to the Contributors section if you're not already there?

**Comment by geemi725** [comment]
I will double check and comment when it's FINALLY ready to go

**Comment by geemi725** [comment]
I added my contributor's name under the 'lab' section since there is no contributor section in the model schema. If that's ok I think it is all set now.

**Pull request merged**
