### PR TITLE
Bonvinlab screen

### PR DESCRIPTION
**Pull request by pkoukos**
## Description
This is a computational docking screen from the [bonvin group](https://www.bonvinlab.org/).
See also [here](https://www.bonvinlab.org/covid/) for more details. We have screened most
of the approved compounds in [Drugbank](https://www.drugbank.ca/) against 3 of the
most important COVID-related targets:

1. 3CLpro/Mpro
2. RdRp
3. Human ACE2

The outcome of the simulation has been deposited in Zenodo (also under the community
of this organisation).

## Status
- [x] YAML file for each piece of data
- [x] Ready to go

Just one thing of note. We have set the `length` parameter in the `simulation` YAML files to nothing.
Not sure if this is going to cause issues on your end. It seems to render fine when we preview the
website with hugo locally though. The reason we have set it to none is because our simulations
fall under the docking category and therefore length is not particularly meaningful.

### CODE REVIEW

**Comment by pkoukos** [comment]
Also tagging @amjjbonvin

The reason the pull request is failing is quite clear: The `length` and `temperature` parameters
for the simulation YAML files. Now, according to the simulation README.md `temperature` can be N/A
which is what we’ve used but apparently this turned out to also be a problem. For `length` we have left
the record empty, as in:

```yaml
files:
    - https://bonvinlab.org/covid/README_ace2.pdf
trajectory: https://zenodo.org/record/3929463/files/ace2.tar.xz?download=1
size: 23 GB
length:
ensemble: Other
temperature: N/A
```

Thing is, the `length` parameter is not as meaningful for a docking simulation (as this is) as it is for an MD one.

Do you think a small adjustment to the schema could be made to allow N/A for both `length` and `temperature`
simulations of type `docking`?

**Comment by sjayellis** [comment]
I have updated the validator to allow for N/A entries for length when the simulation type is docking. For both length and temperature, leaving the entry blank will be accepted as N/A and render as such on the hub. I have updated the README to try and improve the clarity of this.

**Comment by sjayellis** [comment]
Please take a look at the preview site (the netlify details) and let me know if it looks correct. If so I think we can get this merged in right away.

**Comment by pkoukos** [comment]
Everything looks good on our end so you can go ahead and merge.

Thanks for the quick action on this.

**Pull request merged**
