### PR TITLE
added_Bahar_lab_antibody_study

### PR DESCRIPTION
**Pull request by jamesmkrieger**
## Description
Added homology models and docking complexes from our Structure paper: "A monoclonal antibody against staphylococcal enterotoxin B superantigen inhibits SARS-CoV-2 entry in vitro"

## Status
- [x] YAML file for each piece of data
- [x] Updated YAML file for contributors
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
Thanks for the addition. Something strange is going on with the validation script though. It should have caught a couple of proteins which could not be handled, but it's letting them through, and failing on my local copy. GHA may be behaving strangely, I'm looking into it.

**Comment by jamesmkrieger** [comment]
ok. Thanks

**Comment by Lnaden** [comment]
There we go. Found a bug in the validation script and tweaked it. 

Notably there are a few proteins we're not tracking:
*  "furin" looks for "Furin" (sorry, the case is sensitive, its a bunch of back-end engineering to allow both which adds quite a lot to code complexity, I tried.)
* HCoV-OC43 spike
* antibody 6D3

For the two protein's not in the system, there are a couple ways we can proceed.
* Either rename them to their more generic terms (like spike) and/or remove them (like the antibody)
* Add formal entries for them to the Hub.

I'm fine with either, we just have to talk about how to correctly categorize them.

**Comment by jamesmkrieger** [comment]
I agree with making it more general for the HCoV-OC43 spike to just be spike. We have an organism entry I saw where we could put in HCoV-OC43 I guess. 

Maybe we can add a general category for antibody rather than removing that completely.

**Comment by Lnaden** [comment]
If it makes sense to have an antibody category, lets add an antibody category! 

It will take a couple days for me to engineer the category to appear on the site, but I want to get your models up quicker. So I propose these changes for you to make, then we can merge:
* Change the protein entry on your models to just `antibody`
* Add the following line to the bottom of this class: https://github.com/jamesmkrieger/covid/blob/master/schema/validation.py#L27
    * antibody = "antibody"

Once that is in, the schema should pass, then we can merge this while I work on rendering the antibodies category correctly on the site.

**Comment by jamesmkrieger** [comment]
I've now done that in my first commit and also made a second commit to add new organisms to handle the HCoV-OC43 information and also that the antibody comes from mouse. 

Also, apologies for making .yaml files rather than .yml - I can fix that too if you like.

**Comment by Lnaden** [comment]
No need to change the suffix. Its why the validation was not running and it needed to be included anyways. 

You will need to change `furin` to `Furin`, but otherwise this looks good.

**Pull request merged**
