### PR TITLE
Chodera lab contributions to the main repo

### PR DESCRIPTION
**Pull request by hannahbrucemacdonald**
## Description
This PR will transfer contributions that are ready into the main MolSSI covid website project.

## Status
- [x] Adheres to the requested folder structure
- [x] Metadata is provided for each file
- [x] Ready to go

### CODE REVIEW

**Comment by hannahbrucemacdonald** [comment]
This PR currently adds details on two drug molecules

**Comment by Lnaden** [comment]
Is this ready?

**Comment by hannahbrucemacdonald** [comment]
Yeah it is, but can you leave it open? I can just ping you whenever we've added more stuff and we are getting all ticks, to be merged if that works for you?

**Comment by Lnaden** [comment]
I can, you'll have to rebase after every time i do that though.

**Comment by hannahbrucemacdonald** [comment]
Yeah that's ok, I will rebase before I ping you

**Comment by Lnaden** [comment]
ugh... GitHub automatically detected the changes and marked this as "merged." I dont think there is a way I can actually keep this open *and* merge in. I think you'll just have to make a PR every time you all are ready to merge something.

**Comment by hannahbrucemacdonald** [comment]
Yeah I think I confused myself... I'll just open a PR when needed, and @ you when I'm getting green ticks! Thanks

**Comment by Lnaden** [comment]
That'll do!

**Pull request merged**
