### PR TITLE
Create A7_nAChR-spike.yml

### PR DESCRIPTION
**Pull request by asfo1979**
Interaction between the SARS-CoV-2 spike and the α7 nicotinic receptor

## Description
MD simulation of the complex between the Y674-R685 region of the SARS-CoV-2 spike and the extracellular domain of the human α7 nicotinic acetylcholine receptor.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
I see the problems here with the validation:

* Temperature, pressure, and salinity all have implied units of K, atm, and M. You just need to drop the unit designation in your file so they are treated as numbers instead of strings.
* You will need to provide some structure(s) the simulations are based on.

**Comment by Lnaden** [comment]
Looks like the `references` needs to be a list (in case there are multiple references). And with all the possible syntax characters in there, you should wrap the whole reference in quotes to treat it as a string. You'll have to escape the quote marks in the reference itself.

**Comment by Lnaden** [comment]
Awesome! Looks like everything is passing now. You can see how your entry will look here: https://deploy-preview-203--molssi-covid.netlify.app/simulations/#interaction-between-the-sars-cov-2-spike-and-the-%ce%b17-nicotinic-receptor

Let me know if this all looks good to you and I'll go ahead and merge it.

**Comment by asfo1979** [comment]
Hi Levi

All looks good. You can go ahead and merge it.

Thanks for your help!

Best wishes,
Sofia

A Sofia F Oliveira
Senior Research Associate

School of Biochemistry & Center for Computational Chemistry (School of Chemistry)
University of Bristol
University Walk
BS8 1TDS
Bristol, UK

Contacts:
Mobile phone: 07984597145
Email: sofia.oliveira@bristol.ac.uk<mailto:sofia.oliveira@bristol.ac.uk>
Skype: anasofiafoliveira


________________________________

**Pull request merged**
