### PR TITLE
Create tocilizumab.yml

### PR DESCRIPTION
**Pull request by cmanci**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] Adheres to the requested folder structure
- [ ] Metadata is provided for each file
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
Since the 2 proteins on this one are 
```
  -sIL-6R
  -mIL-6R
```

And I dont have maps/pages for those. Can you give me a sense of virus vs host, and important vs not important for them? 

I'd ask you to make the anchoring pages for them, but I can tackle that myself.

**Comment by hannahbrucemacdonald** [comment]
@cmanci says that the targets of these are human immuno thingys, rather than a viral target so I think it's an edge case... we can have a think about the best way to label these, but I don't think these molecules should 'point' to a particular covid-protein or covid-target

**Comment by Lnaden** [comment]
Did the targets for this get resolved?

**Comment by hannahbrucemacdonald** [comment]
Not sure. @cmanci and @apayne97 do you know what we list as the target when it's non-viral?

**Pull request merged**
