### PR TITLE
Corrected yml files

### PR DESCRIPTION
**Pull request by gorangiud**
## Description
Provide a brief description of the data being added here.

## Status
- [x] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
I think the only change you need to make is the protein needs to be `3CLpro` instead of `CLpro`. I know its a bit pedantic, but the way the site makes relations is really fragile due to the static language underneath, so it has to be very precise.

Other than that, this should be good once the changes are made.

**Comment by Lnaden** [comment]
Okay, this all looks good! If this is ready to go from your eyes in the preview, I'll merge it.

**Comment by gorangiud** [comment]
Yes, this should be fine Levi, thank you so much again. The previous one
was a very dumb typo!

I really appreciate your patience. I really know that I was quite some work
to deal with.

Thank you!

Goran


Il giorno mer 6 apr 2022 alle ore 17:39 Levi Naden ***@***.***>
ha scritto:

**Comment by Lnaden** [comment]
Great! The changes will be live in a few minutes

**Pull request merged**
