### PR TITLE
adding yml files and update team

### PR DESCRIPTION
**Pull request by jiayeguo**
## Description
adding 6Y2G.yml to structures/

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
Thanks!

A few things: 

* I think you need to rebase with the current master
* Can you remove the rating from the structure you have in here?
* It looks like you made a change to the schema in `data/targets/3CLpro_protease_activity.yml` Can you verify this adheres to the schema? The rebase should get the validation script running which should help with this step.

**Comment by Lnaden** [comment]
@jiayeguo  could you please made the requested changes? I'd love to get this in!

**Comment by jiayeguo** [comment]
> @jiayeguo could you please made the requested changes? I'd love to get this in!

Sorry about the delay! All done. (I git pulled from the master freshly and remade my changes). Thanks!

**Comment by Lnaden** [comment]
The `data/targets/3CLpro_protease_activity.yml` was modified and appears to no longer conform to the schema. Could you please take another pass at that file to double check that it conforms to the schema?

**Comment by Lnaden** [comment]
On closer inspection, it looks like this and #42 share similar and clashing data. Can you coordinate with @apayne97 to figure out what needs to come from where in each PR?

**Comment by jiayeguo** [comment]
> On closer inspection, it looks like this and #42 share similar and clashing data. Can you coordinate with @apayne97 to figure out what needs to come from where in each PR?

Hey Alex @apayne97, I am wondering if you have updated this file:  `data/targets/3CLpro_protease_activity.yml` in one of your recent PRs?  There seems to be some conflicts in the current master.

**Comment by apayne97** [comment]
@Lnaden @jiayeguo @jchodera 
if you look at the checks, the real problem is with the schema validation - we're failing all over the board in a lot of our commits bc of the schema.

**Comment by apayne97** [comment]
@jiayeguo @Lnaden fixing now, if it works please merge

**Comment by Lnaden** [comment]
@apayne97 can you please correct 6Y2G.yml and 5R8T.yml, they're failing validation due to the proteins field and both are failing because their first `targets` field are not valid targets.

**Comment by apayne97** [comment]
> @apayne97 can you please correct 6Y2G.yml and 5R8T.yml, they're failing validation due to the proteins field and both are failing because their first `targets` field are not valid targets.

@Lnaden on it

**Comment by apayne97** [comment]
@Lnaden where are you getting protein names from? the protein files?

**Comment by Lnaden** [comment]
> @Lnaden where are you getting protein names from? the protein files?

Yes, in the `protein` field

**Comment by Lnaden** [comment]
One advantage to having a well defined schema (and sticking to it): we can expect certain fields and gather data from them.

**Comment by apayne97** [comment]
@Lnaden the problem is that there's an antibody that is a checkpoint inhibitor and doesn't target any protein that we are interested in as of yet (PD-1 - i've added it to the protein/ dir) but it might be relevant

**Comment by apayne97** [comment]
this is why i argued for having a defined schema from the beginning. one of the apparent advantages of yml files was not having to worry about building a framework first but now we have to do it after a bunch of files have been added

**Comment by Lnaden** [comment]
Thats fine. The only reason all the cross linking works is that everything is structured and has consistent names. Its why I pushed for the validator.

Yes, there is going to be some pain with the existing fails, but its either pay for it now, or have nothing work later and its much harder to sift through thousands.

So you have 2 options: Either add all the files necessary to make the checks pass, or propose a schema change

**Comment by Lnaden** [comment]
Ha ha! Success! We good to go, Alex?

**Comment by apayne97** [comment]
@Lnaden we're go, flight

**Comment by Lnaden** [comment]
great. ill clear up the conflicting file here. Not sure why its complaining, but I got it

**Comment by Lnaden** [comment]
I'll merge this for now and cycle back to the outstanding schema problems

**Pull request merged**
