### PR TITLE
Create nsp14_nsp10_amarolab_psf.yml

### PR DESCRIPTION
**Pull request by ozlemd78**
## Description
PSF file of NSP14-NSP10 complex after water molecules and ions are stripped.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
I think you need to have a `.yaml` suffix on the file name. The Hugo build system is a bit particular like that sometimes.

**Comment by Lnaden** [comment]
You changed the Github title, but the actual file in the commit needs to be changed. If its a bit of a pain to edit the patch itself (if you're using the GitHub web interface for example), you might find it easier to close this PR, add the `yml` or `yaml` extension to the file, then make a new PR.

**Comment by ozlemd78** [comment]
Thanks, I will try.
My first time in Github :)

**Comment by Lnaden** [comment]
Not a problem. Im going to close this one in favor of #247 which I think is the same data.

**Pull request closed without merging**
