### PR TITLE
Forouzesh Truncated 6M0J and Simulation

### PR DESCRIPTION
**Pull request by NeginForouzesh**
50ns Simulation of a (Truncated) Novel Coronavirus Spike Protein to the Human ACE2 Receptor

## Description
- Forouzesh_Onufriev_mmgbsa.yml: 50 ns simulation trajectory of a truncated SARS-CoV-2 spike receptor binding domain to the human ACE2 receptor using the Amber ff14SB force field and the OPC water model.
- 6m0j_Forouzesh.yml: Truncated structure of SARS-CoV-2 spike receptor-binding domain bound with the human ACE2 receptor.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by NeginForouzesh** [comment]
It seems that the schema validation failed. The error message is not clear to me, though. Could you give me more details?

**Comment by Lnaden** [comment]
Some small schema things and YAML syntax issues. I've resolved them to save some time, lets see how this looks before we merge it.

**Comment by Lnaden** [comment]
Looks like they are there in the previews now.

Model: https://deploy-preview-155--molssi-covid.netlify.app/models/#sars-cov-2-spike-receptor-binding-domain-bound-with-ace2-spike-spike-binding

Simulation: https://deploy-preview-155--molssi-covid.netlify.app/simulations/#mmgbsa-consensus-estimate-of-the-binding-free-energy-between-the-novel-coronavirus-spike-protein-to-the-human-ace2-receptor-spike-spike-binding

If that looks good to you, I'll go ahead and merge!

**Comment by NeginForouzesh** [comment]
Levi,

Everything looks great!
Please go ahead and merge my pull request.
Thanks!

**Pull request merged**
