### PR TITLE
Added BOKU Spike-ACE2 simulation

### PR DESCRIPTION
**Pull request by janus91**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
This is great! Your preview is here:

https://deploy-preview-164--molssi-covid.netlify.app/simulations/#trajectories-of-the-spike-protein-in-complex-with-human-ace2-spike-spike-binding

Is there any change you want to make or feel the data added are not sufficiently accurate? Or is this ready to publish?

**Comment by janus91** [comment]
Great, I still wanted to add input files and I just found a typo that I will correct still. Thank you!

**Comment by Lnaden** [comment]
Not a problem. Let me know when this is ready to go and I'll get it merged.

**Comment by janus91** [comment]
Hi, I think this should be now good to go. Thanks a lot!

**Comment by Lnaden** [comment]
Thank you!

**Pull request merged**
