### PR TITLE
add 6m0j and 1r42 refined models

### PR DESCRIPTION
**Pull request by zhang-ivy**
## Description
Add yaml files for 6m0j and 1r42 refined models

## Status
- [x] YAML file for each piece of data
- [x] Ready to go

### CODE REVIEW

**Comment by zhang-ivy** [comment]
@jchodera let me know if I also need to add the RBD:ACE2 with glycosylation structures (WT + 3 mutants) that we used in the 17311 simulations. If so, is it ok to link the equilibrated structures (with solvent) before running on fah or do they need to be solvent-less?

**Comment by jchodera** [comment]
> @jchodera let me know if I also need to add the RBD:ACE2 with glycosylation structures (WT + 3 mutants) that we used in the 17311 simulations. If so, is it ok to link the equilibrated structures (with solvent) before running on fah or do they need to be solvent-less?

Ideally, we'd link to the structures without solvent!

Could you also add the references to these models [here](https://github.com/MolSSI/covid/blob/023f74bc0958e05a23117971bfc5abc98ed2d288/data/simulations/FAH_SARS-CoV-2_ACE2_RBD.yml#L86-L92) under a new `models:` section, as in [this entry](https://github.com/MolSSI/covid/blob/9455a44c253a4ffb234f60472756408b0171d5cc/data/simulations/DESRES-ANTON-10875753-no-water.yml#L12-L13)?

**Comment by zhang-ivy** [comment]
@jchodera  Added refined+glycosylated 6m0j RBD and 1r42 ACE structures (without solvent)
Could you review? @glass-w too, please.

**Comment by glass-w** [comment]
@zhang-ivy all looks good to me

**Comment by zhang-ivy** [comment]
@Lnaden  This is ready to be merged!

**Pull request merged**
