### PR TITLE
Create SPIKE_opening_we_continuous_path_amaro_chong_labs.yml

### PR DESCRIPTION
**Pull request by tsztain**
## Description
Provide a brief description of the data being added here.

## Status
- [ ] YAML file for each piece of data
- [ ] Ready to go

### CODE REVIEW

**Comment by Lnaden** [comment]
Looks good to me. Is this ready to go/

**Comment by Lnaden** [comment]
Wanted to ping again, is this ready to be merged?

**Comment by Lnaden** [comment]
Pinging one more time, is this ready to go?

**Comment by tsztain** [comment]
> Pinging one more time, is this ready to go?

Yes!! Sorry did not get notifications for this, it is ready to go!

**Pull request merged**
